# The testing matrix considers ruby/puppet versions supported by SIMP and PE:
# ------------------------------------------------------------------------------
# Release       Puppet   Ruby   EOL
# SIMP 6.4      5.5      2.4    TBD
# PE 2018.1     5.5      2.4    2020-11 (LTS)
# PE 2019.2     6.10     2.5    2019-08 (STS)
#
# https://puppet.com/docs/pe/2018.1/component_versions_in_recent_pe_releases.html
# https://puppet.com/misc/puppet-enterprise-lifecycle
# https://puppet.com/docs/pe/2018.1/overview/getting_support_for_pe.html
# ==============================================================================

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push: {}
  label:
    types:
      - created
      - edited
      - deleted

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        puppet:
          - label: "SIMP 6.4/PE 2018.1"
            puppet_version: "5.5"
            ruby_version: "2.4"
          - label: "SIMP 6.4/PE 2018.1"
            puppet_version: "5.5"
            ruby_version: "2.4"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
